openapi: 3.1.0
info:
  version: 2.0.0
  title: Data API
  description: Webflow's Data API v2
  termsOfService: 'https://webflow.com/legal/terms'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://api.webflow.com/v2'
security:
  - OAuth2: []
  - ApiKey: []
tags:
  - name: Meta
  - name: Sites
  - name: Assets
  - name: Forms
  - name: Pages
  - name: Collections
  - name: Items
  - name: Users
  - name: Products & SKUs
  - name: Orders
  - name: Inventory
  - name: Settings
  - name: Webhooks
  - name: Custom Code
  - name: Custom Code - Sites
  - name: Custom Code - Pages
paths:
  /token/authorized_by:
    get:
      security:
        - OAuth2:
            - 'authorized_user:read'
      operationId: authorized_by
      summary: Authorization User Info
      description: 'Information about the Authorized User <br><br> Required Scope | `authorized_user:read`'
      tags:
        - Meta
  /token/introspect:
    get:
      operationId: introspect
      summary: Authorization Info
      description: |
        Information about the authorization token </br></br> Access to this endpoint requires a bearer token from a Data Client App.
      tags:
        - Meta
  /sites:
    get:
      security:
        - OAuth2:
            - 'sites:read'
      operationId: list-sites
      summary: List Sites
      description: 'List of all sites the provided access token is able to access. </br></br> Required scope | `sites:read`'
      tags:
        - Sites
  '/sites/{site_id}':
    get:
      security:
        - OAuth2:
            - 'sites:read'
      operationId: get-site
      summary: Get Site
      description: 'Get a site by site id </br></br>  Required scope | `sites:read`'
      tags:
        - Sites
  '/sites/{site_id}/custom_domains':
    get:
      security:
        - OAuth2:
            - 'sites:read'
      operationId: get-custom-domains
      summary: Get Custom Domains
      description: 'Get a list of all custom domains related to site. </br></br>  Required scope | `sites:read`'
      tags:
        - Sites
  '/sites/{site_id}/publish':
    post:
      security:
        - OAuth2:
            - 'sites:write'
      operationId: site-publish
      summary: Publish site
      description: 'Publish a site to one more more domains. </br></br>  Required scope | `sites:write`'
      tags:
        - Sites
  '/sites/{site_id}/activity_logs':
    get:
      summary: Get Site Activity Logs
      operationId: get-site-activity-logs
      description: 'Retrieve Activity Logs for a specific Site. Requires Site to be on an Enterprise plan. </br></br>  Required scope | `site_activity:read`'
      tags:
        - Site Activity
        - Sites
      security:
        - OAuth2:
            - 'site_activity:read'
  '/sites/{site_id}/collections':
    get:
      security:
        - OAuth2:
            - 'cms:read'
      operationId: list-collections
      summary: List Collections
      description: 'List of all Collections within a Site. </br></br> Required scope | `cms:read`'
      tags:
        - Collections
        - Sites
    post:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: create-collection
      summary: Create Collection
      description: 'Create a Collection for a site. </br></br> Required scope | `cms:write`'
      tags:
        - Collections
        - Sites
  '/collections/{collection_id}':
    get:
      security:
        - OAuth2:
            - 'cms:read'
      operationId: collection-details
      summary: Get Collection Details
      description: 'Get the full details of a collection from its ID. </br></br> Required scope | `cms:read`'
      tags:
        - Collections
        - Sites
    delete:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: delete-collection
      summary: Delete Collection
      description: 'Delete a collection using its ID. </br></br> Required scope | `cms:write`'
      tags:
        - Collections
        - Sites
  '/collections/{collection_id}/fields':
    post:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: create-field
      summary: Create Collection Field
      description: |
        Create a custom field in a collection.  </br></br> Slugs must be all lowercase letters without spaces. If you pass a string with uppercase letters and/or spaces to the "Slug" property, Webflow will convert the slug to lowercase and replace spaces with "-." </br></br> Only some field types can be created through the API.  This endpoint does not currently support bulk creation.  </br></br>  Required scope | `cms:write`
      tags:
        - Collections
        - Sites
  '/collections/{collection_id}/fields/{field_id}':
    patch:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: update-field
      summary: Update Collection Field
      description: 'Update a custom field in a collection.  </br></br> Required scope | `cms:write`'
      tags:
        - Collections
        - Sites
    delete:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: delete-field
      summary: Delete Collection Field
      description: 'Delete a custom field in a collection. This endpoint does not currently support bulk deletion. </br></br> Required scope | `cms:write`'
      tags:
        - Collections
        - Sites
  '/collections/{collection_id}/items':
    get:
      security:
        - OAuth2:
            - 'CMS:read'
      operationId: list-collection-items
      summary: List Collection Items
      description: 'List of all Items within a Collection. </br></br> Required scope | `CMS:read`'
      tags:
        - Items
        - Collections
        - Sites
    post:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: create-item
      summary: Create Collection Item
      description: 'Create Item in a Collection.</br></br> To create items across multiple locales, <a href="https://developers.webflow.com/data/reference/create-item-for-multiple-locales"> please use this endpoint.</a> </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/collections/{collection_id}/items/live':
    post:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: create-item-live
      summary: Create Collection Item (Live)
      description: 'Create live Item in a Collection. This Item will be published to the live site. </br></br> To create items across multiple locales, <a href="https://developers.webflow.com/data/reference/create-item-for-multiple-locales"> please use this endpoint.</a> </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/collections/{collection_id}/items/bulk':
    post:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: create-item-for-multiple-locales
      summary: Create item for multiple locales
      description: 'Create single Item in a Collection with multiple corresponding locales. </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/collections/{collection_id}/items/{item_id}':
    get:
      security:
        - OAuth2:
            - 'CMS:read'
      operationId: Get-Item
      summary: Get Collection Item
      description: 'Get details of a selected Collection Item. </br></br> Required scope | `CMS:read`'
      tags:
        - Items
        - Collections
        - Sites
    patch:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: update-item
      summary: Update Collection Item
      description: 'Update a selected Item in a Collection. </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
    delete:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: delete-item
      summary: Delete Collection Item
      description: 'Delete an Item from a Collection. This endpoint does not currently support bulk deletion. </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/collections/{collection_id}/items/{item_id}/live':
    patch:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: update-item-live
      summary: Update Collection Item (Live)
      description: 'Update a selected live Item in a Collection. The updates for this Item will be published to the live site. </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
    delete:
      security:
        - OAuth2:
            - 'CMS:write'
      operationId: delete-item-live
      summary: Delete Collection Item (Live)
      description: 'Delete a live Item from a Collection. The Item will be unpublished from the live site. This endpoint does not currently support bulk deletion. </br></br> Required scope | `CMS:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/collections/{collection_id}/items/publish':
    post:
      security:
        - OAuth2:
            - 'cms:write'
      operationId: publish-item
      summary: Publish Item
      description: 'Publish an item or multiple items. </br></br> Required scope | `cms:write`'
      tags:
        - Items
        - Collections
        - Sites
  '/sites/{site_id}/pages':
    get:
      security:
        - OAuth2:
            - 'page:read'
      operationId: list-pages
      summary: List Pages
      description: 'List of all pages for a site </br></br> Required scope | `pages:read`'
      tags:
        - Pages
  '/pages/{page_id}':
    get:
      security:
        - OAuth2:
            - 'page:read'
      operationId: get-page-metadata
      summary: Get Page Metadata
      description: 'Get metadata information for a single page </br></br> Required scope | `pages:read`'
      tags:
        - Pages
    put:
      security:
        - OAuth2:
            - 'page:write'
      description: 'Update Page-level metadata, including SEO and Open Graph fields. </br></br> Required scope | `pages:write`'
      summary: Update Page Metadata
      operationId: update-page-settings
      tags:
        - Pages
  '/pages/{page_id}/dom':
    get:
      security:
        - OAuth2:
            - 'page:read'
      summary: Get Page Content
      description: 'Get static content from a static page. </br> If you do not provide a Locale ID in your request, the response will return any content that can be localized from the Primary locale</br></br> Required scope | `pages:read`'
      operationId: get-static-content
      tags:
        - Pages
    post:
      security:
        - OAuth2:
            - 'page:write'
      summary: Update Page Content
      description: 'Update static content on a static page. This endpoint supports sending 1000 nodes per request. </br></br> Required scope | `pages:write`'
      operationId: update-static-content
      tags:
        - Pages
  '/pages/{page_id}/custom_code':
    get:
      security:
        - OAuth2:
            - 'custom_code:read'
      operationId: get-page-custom-code
      summary: Get Custom Code
      description: |
        Get all registered scripts that have been applied to a specific Page.  </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  </br></br>   Access to this endpoint requires a bearer token from a Data Client App. Required scope | `custom_code:read`
      tags:
        - Custom Code - Pages
        - Custom Code
        - Sites
    delete:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: delete-page-custom-code
      summary: Delete Custom Code
      description: |
        Delete the custom code block that an app has created for a page </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  </br></br>   Access to this endpoint requires a bearer token from a Data Client App. Required scope | `custom_code:write`
      tags:
        - Custom Code - Pages
        - Custom Code
        - Sites
    put:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: add-custom-code-to-page
      summary: Add/Update Custom Code
      description: |
        Add a registered script to a Page.  </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  </br></br>   Access to this endpoint requires a bearer token from a Data Client App. Required scope | `custom_code:write`
      tags:
        - Custom Code - Pages
        - Custom Code
        - Sites
  '/sites/{site_id}/custom_code':
    get:
      security:
        - OAuth2:
            - 'custom_code:read'
      operationId: get-site-custom-code
      summary: Get Custom Code
      description: |
        Get all registered scripts that have been applied to a specific Site.  </br></br> Access to this endpoint requires a bearer token from a Data Client App.       Required scope | `custom_code:read`
      tags:
        - Custom Code - Sites
        - Custom Code
        - Sites
    delete:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: delete-site-custom-code
      summary: Delete Custom Code
      description: |
        Delete the custom code block that an app created for a Site </br></br> Access to this endpoint requires a bearer token from a Data Client App.       Required scope | `custom_code:write`
      tags:
        - Custom Code - Sites
        - Custom Code
        - Sites
    put:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: add-custom-code-tosite
      summary: Add/Update Custom Code
      description: |
        Add a registered script to a Site.  </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  </br></br>   Access to this endpoint requires a bearer token from a Data Client App.         Required scope | `custom_code:write`
      tags:
        - Custom Code - Sites
        - Custom Code
        - Sites
  '/sites/{site_id}/registered_scripts':
    get:
      security:
        - OAuth2:
            - 'custom_code:read'
      operationId: get-scripts
      summary: Get Registered Scripts
      description: |
        List of scripts registered to a Site.  </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  Additionally, Scripts can be remotely hosted, or registered as inline snippets.     Access to this endpoint requires a bearer token from a Data Client App.     </br></br>  Required scope | `custom_code:re[...]
      tags:
        - Custom Code
        - Registered Scripts
  '/sites/{site_id}/registered_scripts/hosted':
    post:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: post-hosted-script
      summary: Register Script - Hosted
      description: |
        Add a script to a Site's Custom Code registry. </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  Additionally, Scripts can be remotely hosted, or registered as inline snippets.   Access to this endpoint requires a bearer token from a Data Client App.   </br></br>  Required scope | `custom_cod[...]
      tags:
        - Custom Code
        - Registered Scripts
  '/sites/{site_id}/registered_scripts/inline':
    post:
      security:
        - OAuth2:
            - 'custom_code:write'
      operationId: post-inline-scripts
      summary: Register Script - Inline
      description: |
        Add a script to a Site's Custom Code registry. Inline scripts can be between 1 and 2000 characters. </br></br>  In order to use the Custom Code APIs for Sites and Pages, Custom Code Scripts must first be registered  to a Site via the `registered_scripts` endpoints, and then applied to a Site or Page using the appropriate `custom_code` endpoints.  </br></br>  Access to this endpoint requires a bearer token from a Data Client App. Required scope | `custom_code:write`
      tags:
        - Custom Code
        - Registered Scripts
  '/sites/{site_id}/custom_code/blocks':
    get:
      security:
        - OAuth2:
            - 'custom_code:read'
      operationId: get-site-custom-code-blocks
      summary: List Custom Code Blocks
      description: |
        Get all instances of Custom Code applied to a Site or Pages.  </br></br> Access to this endpoint requires a bearer token from a Data Client App. Required scope | `custom_code:read`
      tags:
        - Custom Code
  '/sites/{site_id}/assets':
    get:
      security:
        - OAuth2:
            - 'assets:read'
      operationId: list-assets
      summary: List Assets
      description: 'List assets for a given site </br></br> Required scope | `assets:read`'
      tags:
        - Assets
    post:
      security:
        - OAuth2:
            - 'assets:write'
      operationId: create-asset
      summary: Create Asset Metadata
      description: |
        Create a new asset entry.  </br></br> This endpoint generates a response with the following information: `uploadUrl` and `uploadDetails`.  You can use these two properties to [upload the file to Amazon s3 by making a POST](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html) request to the `uploadUrl` with the `uploadDetails` object as your header information in the request. </br></br>  Required scope | `assets:write`
      tags:
        - Assets
  '/assets/{asset_id}':
    get:
      security:
        - OAuth2:
            - 'assets:read'
      operationId: get-asset
      summary: Get Asset
      description: 'Get an Asset </br></br> Required scope | `assets:read`'
      tags:
        - Assets
    patch:
      security:
        - OAuth2:
            - 'assets:write'
      operationId: patch-asset
      summary: Update Asset
      description: 'Update an Asset </br></br> Required scope | `assets:write`'
      tags:
        - Assets
    delete:
      security:
        - OAuth2:
            - 'assets:write'
      operationId: delete-asset
      summary: Delete Asset
      description: Delete an Asset
      tags:
        - Assets
  '/sites/{site_id}/asset_folders':
    get:
      security:
        - OAuth2:
            - 'assets:read'
      operationId: list-asset-folders
      summary: List Asset Folders
      description: 'List Asset Folders within a given site <br><br> Required scope | `assets:read`'
      tags:
        - Asset Folders
    post:
      security:
        - OAuth2:
            - 'assets:write'
      operationId: create-asset-folder
      summary: Create Asset Folder
      description: 'Create an Asset Folder within a given site <br><br> Required scope | `assets:write`'
      tags:
        - Asset Folders
  '/asset_folders/{asset_folder_id}':
    get:
      security:
        - OAuth2:
            - 'assets:read'
      operationId: get-asset-folder
      summary: Get Asset Folder
      description: 'Get details about a specific Asset Folder <br><br> Required scope | `assets:read`'
      tags:
        - Asset Folders
  '/sites/{site_id}/webhooks':
    get:
      operationId: list-webhooks
      summary: List Webhooks
      description: |
        List all App-created Webhooks registered for a given site </br></br> Required scope | `sites:read`
      tags:
        - Webhooks
    post:
      operationId: create-webhook
      summary: Create Webhook
      description: |
        Create a new Webhook, to be notified when Webflow resources change. Limit of 75 registrations per `triggerType`, per site. </br></br> Access to this endpoint requires a bearer token from a Data Client App. The only exceptions are for creating webhooks with `site_publish` or `form_submission` triggers, which can be done with Site Tokens </br> Required scope | `sites:write`
      tags:
        - Webhooks
  '/webhooks/{webhook_id}':
    get:
      operationId: get-webhook
      summary: Get Webhook
      description: Get a specific Webhook instance
      tags:
        - Webhooks
    delete:
      operationId: remove-webhook
      summary: Remove Webhook
      description: Remove a Webhook
      tags:
        - Webhooks
  '/sites/{site_id}/forms':
    get:
      security:
        - OAuth2:
            - 'forms:read'
      operationId: list-forms
      summary: List Forms
      description: 'List forms for a given site </br></br> Required scope | `forms:read`'
      tags:
        - Forms
  '/forms/{form_id}':
    get:
      security:
        - OAuth2:
            - 'forms:read'
      operationId: get-form-schema
      summary: Get Form Schema
      description: 'Get information about a given form</br></br> Required scope | `forms:read`'
      tags:
        - Forms
  '/forms/{form_id}/submissions':
    get:
      security:
        - OAuth2:
            - 'forms:read'
      operationId: list-submissions
      summary: List Form Submissions
      description: 'List form submissions for a given form </br></br> Required scope | `forms:read`'
      tags:
        - Forms
  '/form_submissions/{form_submission_id}':
    get:
      security:
        - OAuth2:
            - 'forms:read'
      operationId: get-form-submission
      summary: Get Form Submission
      description: 'Get information about a given form submission</br></br> Required scope | `forms:read`'
      tags:
        - Forms
    patch:
      security:
        - OAuth2:
            - 'forms:write'
      operationId: modify-form-submission
      summary: Modify Form Submission
      description: 'Update hidden fields on a form submission</br></br> Required scope | `forms:write`'
      tags:
        - Forms
  '/sites/{site_id}/users':
    get:
      security:
        - OAuth2:
            - 'users:read'
      operationId: list-users
      summary: List Users
      description: 'Get a list of users for a site <br><br> Required scope | `users:read`'
      tags:
        - User Accounts
  '/sites/{site_id}/users/{user_id}':
    get:
      security:
        - OAuth2:
            - 'users:read'
      operationId: get-user
      summary: Get User
      description: 'Get a User by ID <br><br> Required scope | `users:read`'
      tags:
        - User Accounts
    patch:
      security:
        - OAuth2:
            - 'users:write'
      operationId: update-user
      summary: Update User
      description: |
        Update a User by ID <br><br> Required scope | `users:write`
        <aside class="notice">The <code>email</code> and <code>password</code> fields cannot be updated using this endpoint</aside>
      tags:
        - User Accounts
        - Access Groups
    delete:
      security:
        - OAuth2:
            - 'users:write'
      operationId: delete-user
      summary: Delete User
      description: 'Delete a User by ID <br><br> Required scope | `users:write`'
      tags:
        - User Accounts
  '/sites/{site_id}/users/invite':
    post:
      security:
        - OAuth2:
            - 'users:write'
      operationId: invite-user
      summary: Create and Invite a User
      description: 'Create and invite a user with an email address. The user will be sent and invite via email, which they will need to accept in order to join paid Access Groups. <br><br> Required scope | `users:write`'
      tags:
        - User Accounts
        - Access Groups
  '/sites/{site_id}/accessgroups':
    get:
      security:
        - OAuth2:
            - 'users:read'
      operationId: list-access-groups
      summary: List Access Groups
      description: 'Get a list of access groups for a site <br><br> Required scope | `users:read`'
      tags:
        - Access Groups
  '/sites/{site_id}/products':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: list-products
      summary: List Products & SKUs
      description: |
        Retrieve all products for a site. Use `limit` and `offset` to page through all products with subsequent requests. All SKUs for each product will also be fetched and returned. The `limit`, `offset` and `total` values represent Products only and do not include any SKUs.

        Required scope | `ecommerce:read`
      tags:
        - Products & SKUs
    post:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: create-product
      summary: Create Product & SKU
      description: |-
        Creating a new Product involves creating both a Product and a SKU, since a Product Item has to have, at minimum, a single SKU.

        In order to create a Product with multiple SKUs - for example a T-shirt in sizes small, medium and large - you'll need to create `sku-properties`. In our T-shirt example, a single `sku-property` would be Color. Within that property, we'll need to list out the various colors a T-shirt could be as an array of `enum` values: `royal-blue`, `crimson-red`, and `forrest-green`.

        Once, you've created a Product and its `sku-properties` with `enum` values, you can create your default SKU, which will automatically be a combination of the first `sku-properties` you've created. In our example, the default SKU will be a Royal Blue T-Shirt, because our first `enum` of our Color `sku-property` is Royal Blue. After you've created your product, you can create additional SKUs using the <a href="https://developers.webflow.com/reference/create-skus">Create SKU endpoint</a>

        Upon creation, the default product type will be `Advanced`. The product type is used to determine which Product and SKU fields are shown to users in the `Designer` and the `Editor`. Setting it to `Advanced` ensures that all Product and SKU fields will be shown.

        Required scope | `ecommerce:write`
      tags:
        - Products & SKUs
  '/sites/{site_id}/products/{product_id}':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: get-product
      summary: Get Product and SKUs
      description: |
        Retrieve a single product by its id. All of its SKUs will also be retrieved.

        Required scope | `ecommerce:read`
      tags:
        - Products & SKUs
    patch:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: update-product
      summary: Update Product
      description: |
        Updating an existing Product will set the product type to `Advanced`. The product type is used to determine which Product and SKU fields are shown to users in the `Designer` and the `Editor`. Setting it to `Advanced` ensures that all Product and SKU fields will be shown. The product type can be edited in the `Designer` or the `Editor`.

        Required scope | `ecommerce:write`
      tags:
        - Products & SKUs
  '/sites/{site_id}/products/{product_id}/skus':
    post:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: create-skus
      summary: Create SKU
      description: |
        Create additional SKUs to cover every variant of your Product. The Default SKU already counts as one of the variants.

        Creating additional SKUs will set the product type to `Advanced` for the product associated with the SKUs. The product type is used to determine which Product and SKU fields are shown to users in the `Designer` and the `Editor`. Setting it to `Advanced` ensures that all Product and SKU fields will be shown. The product type can be edited in the `Designer` or the `Editor`.

        Required scope | `ecommerce:write`
      tags:
        - Products & SKUs
  '/sites/{site_id}/products/{product_id}/skus/{sku_id}':
    patch:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: update-sku
      summary: Update SKU
      description: |
        Updating an existing SKU will set the product type to `Advanced` for the product associated with the SKU. The product type is used to determine which Product and SKU fields are shown to users in the `Designer` and the `Editor`. Setting it to `Advanced` ensures that all Product and SKU fields will be shown. The product type can be edited in the `Designer` or the `Editor`.

        Required scope | `ecommerce:write`
      tags:
        - Products & SKUs
  '/sites/{site_id}/orders':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: list-orders
      summary: List Orders
      description: |
        List all orders created for a given site.

        Required scope | `ecommerce:read`
      tags:
        - Orders
  '/sites/{site_id}/orders/{order_id}':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: get-order
      summary: Get Order
      description: |
        Retrieve a single product by its id. All of its SKUs will also be retrieved.

        Required scope | `ecommerce:read`
      tags:
        - Orders
    patch:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: update-order
      summary: Update Order
      description: |
        This API lets you update the fields, `comment`, `shippingProvider`, and/or `shippingTracking` for a given order. All three fields can be updated simultaneously or independently.

        Required scope | `ecommerce:write`
      tags:
        - Orders
  '/sites/{site_id}/orders/{order_id}/fulfill':
    post:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: fulfill-order
      summary: Fulfill Order
      description: |
        Updates an order's status to fulfilled

        Required scope | `ecommerce:write`
      tags:
        - Orders
  '/sites/{site_id}/orders/{order_id}/unfulfill':
    post:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: unfulfill-order
      summary: Unfulfill Order
      description: |
        Updates an order's status to unfulfilled

        Required scope | `ecommerce:write`
      tags:
        - Orders
  '/sites/{site_id}/orders/{order_id}/refund':
    post:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: refund-order
      summary: Refund Order
      description: |
        This API will reverse a Stripe charge and refund an order back to a
        customer. It will also set the order's status to `refunded`.


        Required scope | `ecommerce:write`
      tags:
        - Orders
  '/collections/{collection_id}/items/{item_id}/inventory':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: list-inventory
      summary: List Inventory
      description: |
        List the current inventory levels for a particular SKU item.

        Required scope | `ecommerce:read`
      tags:
        - Inventory
    patch:
      security:
        - OAuth2:
            - 'ecommerce:write'
      operationId: update-inventory
      summary: Update Item Inventory
      description: |
        Updates the current inventory levels for a particular SKU item. Updates may be given in one or two methods, absolutely or incrementally. Absolute updates are done by setting `quantity` directly. Incremental updates are by specifying the inventory delta in `updateQuantity` which is then added to the `quantity` stored on the server.

        Required scope | `ecommerce:write`
      tags:
        - Inventory
  '/sites/{site_id}/ecommerce/settings':
    get:
      security:
        - OAuth2:
            - 'ecommerce:read'
      operationId: ecommerce-settings
      summary: Get Ecommerce Settings
      description: |
        Retrieve ecommerce settings for a site.

        Required scope | `ecommerce:read`
      tags:
        - Settings
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            'authorized_user:read': read details about the authorized user
            'read:pages': read pages on the site
            'sites:read': read sites on the site
            'sites:write': modify pages on the site
            'custom_code:read': read custom code on the site
            'custom_code:write': modify custom code on the site
            'custom_code:delete': delete custom code on the site
            'users:read': read users on the site
            'users:write': modify users on the site
            'ecommerce:read': read ecommerce data
            'ecommerce:write': edit ecommerce data
            'site_activity:read': read site activity logs
          authorizationUrl: 'https://webflow.com/oauth/authorize'
          tokenUrl: 'https://api.webflow.com/oauth/token'
    ApiKey:
      type: http
      scheme: bearer
webhooks:
  form_submission:
    post:
      operationId: form_submission
      summary: Form Submission
      description: Information about a form that was subitted
      tags:
        - Forms
        - Sites
  site_publish:
    post:
      operationId: site_publish
      summary: Site Publish
      tags:
        - Sites
  ecomm_new_order:
    post:
      operationId: ecomm_new_order
      summary: New eComm Order
      tags:
        - Orders
  ecomm_order_changed:
    post:
      operationId: ecomm_order_changed
      summary: Updated eComm Order
      tags:
        - Orders
  ecomm_inventory_changed:
    post:
      operationId: ecomm_inventory_changed
      summary: Updated eComm Inventory
      tags:
        - Inventory
  user_account_added:
    post:
      operationId: user_account_added
      summary: New User Added
      tags:
        - Users
  user_account_updated:
    post:
      operationId: user_account_updated
      summary: Account Updated
      tags:
        - Users
  user_account_deleted:
    post:
      operationId: user_account_deleted
      summary: Account Deleted
      tags:
        - Users
  collection_item_created:
    post:
      operationId: collection_item_created
      summary: Item Created
      tags:
        - Items
        - Collections
  collection_item_changed:
    post:
      operationId: collection_item_changed
      summary: Item Updated
      tags:
        - Items
        - Collections
  collection_item_deleted:
    post:
      operationId: collection_item_deleted
      summary: Item Deleted
      tags:
        - Items
        - Collections
  collection_item_unpublished:
    post:
      operationId: collection_item_unpublished
      summary: Item Unpublished
      tags:
        - Items
        - Collections
  page_created:
    post:
      operationId: page_created
      summary: Page Created
      tags:
        - Pages
  page_metadata_updated:
    post:
      operationId: page_metadata_updated
      summary: Page Metadata Updated
      tags:
        - Pages
  page_deleted:
    post:
      operationId: page_deleted
      summary: Page Deleted
      tags:
        - Pages